# Generated by Django 3.2.16 on 2022-10-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_myuser_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone_no',
            field=models.CharField(blank=True, default='00000000', max_length=15),
        ),
    ]
