# Generated by Django 3.2.16 on 2022-10-26 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_myuser_phone_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='accounts.myuser', verbose_name='Profile')),
                ('userType', models.CharField(choices=[('chef', 'chef'), ('customer', 'customer'), ('customer', 'customer'), ('admin', 'admin'), ('author', 'author')], max_length=8)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('followers', models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChefProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='chef_profile', serialize=False, to='accounts.profile', verbose_name='Chef Profile')),
                ('headline', models.CharField(blank=True, max_length=500, null=True)),
                ('languages', models.CharField(blank=True, max_length=500, null=True)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MealPrep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prep', models.CharField(choices=[('weekly', 'weekly'), ('monthly', 'monthly')], default=' ', max_length=7, verbose_name='Service Type')),
                ('service_type', models.CharField(max_length=19)),
                ('price', models.IntegerField(verbose_name='Start Price')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_service', to='accounts.chefprofile', verbose_name='User Service')),
            ],
        ),
    ]
