# Generated by Django 3.2.16 on 2022-10-26 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_chefprofile_is_chef'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chefprofile',
            old_name='user',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='mealprep',
            old_name='user',
            new_name='profile',
        ),
    ]
