# Generated by Django 3.2.16 on 2022-10-26 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20221026_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='userType',
            new_name='user_type',
        ),
    ]
