# Generated by Django 3.2.16 on 2022-10-24 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='SetMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
                ('desc', models.CharField(max_length=255, null=True)),
                ('price', models.FloatField(verbose_name='Starting Price')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cusine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.cuisine')),
            ],
        ),
        migrations.CreateModel(
            name='starterMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125)),
                ('s_price', models.CharField(max_length=125, null=True, verbose_name='Sharing price')),
                ('p_price', models.CharField(max_length=125, null=True, verbose_name='platted price')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='starter_menu', to='menu.setmenu')),
            ],
        ),
        migrations.CreateModel(
            name='sideMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125)),
                ('s_price', models.CharField(max_length=125, null=True, verbose_name='Sharing price')),
                ('p_price', models.CharField(max_length=125, null=True, verbose_name='platted price')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='side_menu', to='menu.setmenu')),
            ],
        ),
        migrations.CreateModel(
            name='MenuReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(null=True)),
                ('review', models.TextField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_reviews', to='menu.setmenu')),
            ],
        ),
        migrations.CreateModel(
            name='mainMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125)),
                ('s_price', models.CharField(max_length=125, null=True, verbose_name='Sharing price')),
                ('p_price', models.CharField(max_length=125, null=True, verbose_name='platted price')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_menu', to='menu.setmenu')),
            ],
        ),
        migrations.CreateModel(
            name='dessertMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125)),
                ('s_price', models.CharField(max_length=125, null=True, verbose_name='Sharing price')),
                ('p_price', models.CharField(max_length=125, null=True, verbose_name='platted price')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dessert_menu', to='menu.setmenu')),
            ],
        ),
        migrations.CreateModel(
            name='addons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_addons', to='menu.setmenu')),
            ],
        ),
    ]
