# Generated by Django 3.2.16 on 2022-10-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setmenu',
            name='status',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
