# Generated by Django 3.2.16 on 2022-10-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_setmenu_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addons',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='dessertmenu',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='mainmenu',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='menureviews',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='sidemenu',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='startermenu',
            name='menu',
        ),
        migrations.AddField(
            model_name='setmenu',
            name='addons',
            field=models.ManyToManyField(related_name='addons', to='menu.addons'),
        ),
        migrations.AddField(
            model_name='setmenu',
            name='dessert_menu',
            field=models.ManyToManyField(related_name='dessert_menu', to='menu.dessertMenu'),
        ),
        migrations.AddField(
            model_name='setmenu',
            name='main_menu',
            field=models.ManyToManyField(related_name='main_menu', to='menu.mainMenu'),
        ),
        migrations.AddField(
            model_name='setmenu',
            name='menu_reviews',
            field=models.ManyToManyField(related_name='menu_reviews', to='menu.MenuReviews'),
        ),
        migrations.AddField(
            model_name='setmenu',
            name='side_menu',
            field=models.ManyToManyField(related_name='side_menu', to='menu.sideMenu'),
        ),
        migrations.AddField(
            model_name='setmenu',
            name='starter_menu',
            field=models.ManyToManyField(related_name='starter_menu', to='menu.starterMenu'),
        ),
        migrations.RemoveField(
            model_name='setmenu',
            name='cusine',
        ),
        migrations.AddField(
            model_name='setmenu',
            name='cusine',
            field=models.ManyToManyField(related_name='cusines', to='menu.Cuisine'),
        ),
    ]
