# Generated by Django 3.2.16 on 2022-10-26 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20221026_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setmenu',
            name='menu_reviews',
        ),
        migrations.AddField(
            model_name='menureviews',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_reviews', to='menu.setmenu'),
        ),
    ]
