# Generated by Django 3.2.16 on 2022-10-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20221026_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setmenu',
            name='addons',
            field=models.ManyToManyField(blank=True, related_name='addons', to='menu.addons'),
        ),
        migrations.AlterField(
            model_name='setmenu',
            name='cusine',
            field=models.ManyToManyField(blank=True, related_name='cusines', to='menu.Cuisine'),
        ),
        migrations.AlterField(
            model_name='setmenu',
            name='dessert_menu',
            field=models.ManyToManyField(blank=True, related_name='dessert_menu', to='menu.dessertMenu'),
        ),
        migrations.AlterField(
            model_name='setmenu',
            name='main_menu',
            field=models.ManyToManyField(blank=True, related_name='main_menu', to='menu.mainMenu'),
        ),
        migrations.AlterField(
            model_name='setmenu',
            name='side_menu',
            field=models.ManyToManyField(blank=True, related_name='side_menu', to='menu.sideMenu'),
        ),
        migrations.AlterField(
            model_name='setmenu',
            name='starter_menu',
            field=models.ManyToManyField(blank=True, related_name='starter_menu', to='menu.starterMenu'),
        ),
    ]
