# Generated by Django 3.2.16 on 2022-10-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_menugallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='setmenu',
            name='menu_gallery',
            field=models.ManyToManyField(related_name='gallery', to='menu.menuGallery'),
        ),
    ]
