# Generated by Django 3.2.16 on 2022-10-30 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_setmenu_menu_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setmenu',
            name='menu_gallery',
        ),
    ]
