# Generated by Django 3.2.16 on 2022-11-10 08:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0011_alter_setmenu_menu_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setmenu',
            name='menu_gallery',
            field=models.ManyToManyField(related_name='gallery', to='menu.MenuGallery'),
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('address_name', models.CharField(max_length=200)),
                ('delivery', models.CharField(choices=[('PHY', 'Physical'), ('GOU', 'Gourmet')], max_length=30)),
                ('time', models.DateTimeField(default=datetime.datetime(2022, 11, 10, 9, 10, 8, 979331))),
                ('description', models.TextField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
