# Generated by Django 3.2.16 on 2022-11-10 23:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_auto_20221110_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='addons',
            name='p_price',
            field=models.CharField(max_length=125, null=True, verbose_name='platted price'),
        ),
        migrations.AddField(
            model_name='addons',
            name='s_price',
            field=models.CharField(max_length=125, null=True, verbose_name='Sharing price'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 11, 0, 1, 17, 71183)),
        ),
        migrations.AlterField(
            model_name='setmenu',
            name='menu_gallery',
            field=models.ManyToManyField(related_name='gallery', to='menu.MenuGallery'),
        ),
    ]
